# Generated by Django 3.2 on 2021-05-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210503_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='order',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='url',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
